# Settings
use_frameworks!

# Define pods
def pods
    pod 'Awesome', :path => '../'
    pod 'Presentables'
    pod 'SnapKit'
end

# tvOS
target 'AwesomeTV_Example' do
    platform :tvos, '11.0'
    pods
end

# macOS
target 'AwesomeMac_Example' do
    platform :macos, '10.13'
    pods
end

#iOS
target 'Awesome_Example' do
    platform :ios, '11.0'
    pods
    
    target 'Awesome_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.2'
    end
end
